### ISSUE TITLE
Fix crash

### ISSUE THREAD

**Issue by albertyw** [albertyw/codemancer#136]
```
file:///var/www/app/codemancer/js/util.ts:72
        const error = new CustomError(message);
                      ^

CustomError: Unrecoverable error when making request
    at CustomError.create (file:///var/www/app/codemancer/js/util.ts:72:23)
    at file:///var/www/app/codemancer/js/util.ts:57:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  metadata: {
    status: 504,
    statusText: 'Gateway Time-out',
```

**Comment by albertyw** [comment]
Fixed in 587a0f3
