### ISSUE TITLE
Circular data restructure from weather API

### ISSUE THREAD

**Issue by albertyw** [albertyw/codemancer#138]
```
207.231.172.42 - - [13/May/2024:17:27:28 +0000] "GET /airnow/?latitude=37.78&longitude=-122.41 HTTP/1.0" 200 1391 "https://www.codemancer.com/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
/var/www/app/node_modules/express/lib/response.js:1159
    : JSON.stringify(value);
           ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'ClientRequest'
    |     property 'res' -> object with constructor 'IncomingMessage'
    --- property 'req' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (/var/www/app/node_modules/express/lib/response.js:1159:12)
    at ServerResponse.json (/var/www/app/node_modules/express/lib/response.js:272:14)
    at file:///var/www/app/server/handlers.ts:65:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by albertyw** [comment]
Fixed in ed4b08a
